---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  tasks:
    - name: Collect nova-api-proxy coverage artifacts
      synchronize:
        src: "{{ zuul.project.src_dir }}/nova-api-proxy/{{ item }}"
        dest: "{{ zuul.executor.log_root }}/{{ item }}"
        mode: pull
        copy_links: true
        verify_host: true
      loop:
        - UTCoverage/
        - UTCoverage/coverage.xml
      ignore_errors: true
