#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2019 Intel Corporation
#
# Copyright (c) 2019 Wind River Systems, Inc.
#

# Devstack settings

# This plugin enables StarlingX nfv services and follows the
# DevStack plugin contract:
# https://docs.openstack.org/devstack/latest/plugins.html#plugin-sh-contract

# Services

# Defaults
# --------

STX_NFV_NAME=nfv

######### Plugin Specific ##########
enable_service $STX_NFV_NAME

# This must not use any variables to work properly in OpenStack's DevStack playbook
define_plugin nfv
# This works for Zuul jobs using OpenStack's DevStack roles
plugin_requires nfv update
plugin_requires nfv fault
plugin_requires nfv metal

if is_service_enabled nfv; then
    # Enable prerequisites here
    :
fi

# NOTE(dtroyer): This needs to be refined a bit yet, for example fo we want
#                to abort or just disable guest-agent and guest-server if the
#                prereqs are not configured?
if is_service_enabled guest-agent || is_service_enabled guest-server; then
    # These guest- services require additional prerequisites
    # metal: to install mtce_common header files and libraries
    # fm-common: to install fmcommon library
    local req_services="metal fm-common"
    for srv in $req_services;do
        if ! is_service_enabled "$srv"; then
            die $LINENO "$srv should be enabled for guestAgent/guestServer"
        fi
    done
fi

# Initial source of lib script
source $DEST/nfv/devstack/lib/nfv
