[tox]
envlist = pep8,pylint,black
minversion = 4.4.0
skipsdist = True
toxworkdir = /tmp/{env:USER}_novaapiproxytox

[novaapiproxy]
nova_api_proxy_base_dir = .
nova_api_proxy_dir = ./nova-api-proxy

[testenv]
basepython = python3.9
sitepackages = False
deps =
    -c{env:UPPER_CONSTRAINTS_FILE:https://opendev.org/starlingx/root/raw/branch/master/build-tools/requirements/debian/upper-constraints.txt}
    -r{toxinidir}/test-requirements.txt

[flake8]
show-source = True
max-line-length = 88
# Suppressed flake8 codes
# E203 whitespace before ':'; conflict with Black
# H301 one import per line; conflict with Black
# W503 line break before binary operator; conflict with Black
ignore = E203,H301,W503

[testenv:pep8]
commands =
    flake8 {[novaapiproxy]nova_api_proxy_base_dir}

[testenv:pylint]
deps = {[testenv]deps}
    eventlet
    oslo.config
    oslo.log
    paste
    PasteDeploy
    routes
    webob
commands = pylint {[novaapiproxy]nova_api_proxy_dir} --rcfile=.pylintrc

[testenv:black]
# This environment checks and displays the recommended changes by Black for formatting
# Python files.
# To apply the format in a specific file, use the following command: black {posargs} .
deps =
   black>=23.11.0 # MIT
commands =
   black --check --diff .
